apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saegim

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - storage-pvc.yaml
  - postgres-statefulset.yaml
  - migration-job.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

images:
  - name: saegim-backend
    newTag: latest
  - name: saegim-frontend
    newTag: latest
