apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: saegim
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: saegim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
